version: "3"

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}


volumes:
  mysql_volume:
    driver: ${VOLUMES_DRIVER}
  redis_volume:
    driver: ${VOLUMES_DRIVER}
  rabbitmq_volume:
    driver: ${VOLUMES_DRIVER}
# 服务编排
services:

# NGINX #############################################
  nginx:
    build: 
      context: ./nginx
      # args:
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - go_server
    volumes:
      # 挂载运行代码目录
      - ${APP_CODE_PATH_HOST}:/var/www
      # 挂载日志目录
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ./nginx/sites/:/etc/nginx/sites/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - frontend
      - backend

  go_server:
    build: 
      context: ./go_server
      args:
        - APP_PATH=${GO_APP_PATH}
    ports:
      - 9090:9090
    networks:
      - backend
    

